---
- name: Install certbot's required packages
  import_tasks: packages.yml

- name: Get certificate expiration date
  command: openssl x509 -checkend 172800 -noout -in /etc/letsencrypt/live/jhcloud.io/fullchain.pem
  register: cert_check
  changed_when: cert_check.rc != 0
  failed_when: cert_check.stdout_lines|length > 0

- name: Create / renew test letsencrypt certificate
  import_tasks: create-certificate-test.yml
  when: cert_check.rc != 0 and CI

- name: Create / renew letsencrypt certificate
  import_tasks: create-certificate.yml
  when: cert_check.rc != 0 and not CI
