---
- name: Install EPEL (Extra Packages for Enterprise Linux) repository.
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: yes
    gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
  when: install_epel

- name: Install certbot packages
  yum:
    name: "{{ certbot_packages }}"

- name: Create letsencrypt certificate
  shell: >
    certbot certonly --non-interactive --agree-tos --email "{{certbot_email}}"
    --domains "{{ certbot_certs | join ',' }}"
    --dns-route53 --server https://acme-v02.api.letsencrypt.org/directory
  environment:
    AWS_ACCESS_KEY_ID: "{{certbot_aws_access_key}}"
    AWS_SECRET_ACCESS_KEY: "{{certbot_aws_secret_key}}"
